### ISSUE TITLE
Allow implementing on_next() and handling data ourselves with the ButtonMenu

### ISSUE THREAD

**Issue by RaymondLWong** [robertwayne/dpymenus#24]
It would be useful if I could setup the `Page` data myself when the `next()` function is called. If my data comes from a database or other paginated source (such as a REST API), I want to be able to update the current `Embed` with new data. One way to do this is to implement our own `next()` event handler.

**Comment by robertwayne** [comment]
Assuming I'm understanding correctly, you can do this already. On your Page object, just do something like:

```
page1 = Page(title='Example', description='example')
page1.on_next(update_data)
page1.buttons([btn1, btn2])

def update_data(menu: ButtonMenu):
    if menu.button_pressed(btn1):
        e = discord.Embed()
        menu.output.edit(embed=e)
```

Each menu has access to an `output` attr which is a discord Message object. You can call any normal methods on that like `delete`, `edit`, etc. 

I'm writing this on my phone so I haven't tested it, but that should work. Obviously the buttons would remain the same as the page isn't changing, just the embed data, but it sounds like you just needed a button to update that page anyway.

**Comment by RaymondLWong** [comment]
Unfortunately, I get an error when pressing the button. It looks like you might be trying to serialise something?

```python
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/USERNAME/PycharmProjects/PROJECT_NAME/src/main.py", line 151, in test_me
    await menu.open()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\site-packages\dpymenus\button_menu.py", line 66, in open
    await self.page.on_next_event(self)
  File "C:/Users/USERNAME/PycharmProjects/PROJECT_NAME/src/main.py", line 146, in update_data
    await menu.output.edit(embed=get_page(2))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\message.py", line 886, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\utils.py", line 318, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

**Comment by robertwayne** [comment]
Yeah, you can't pass in a Page object to the embed field. That is something I will add to my list for the next release, however.

I whipped up a basic example based on your initial request that I just tested and works as expected:

```
@bot.command()
async def test(self, ctx):
    reload = '🔄'
    close = '❌'

    async def make_request():
        """We will fake a web API request and return JSON data."""
        return {'mock': 'json', 'web': 'request', 'random_data': randint(1, 100)}

    async def update_data(menu: ButtonMenu):
        if menu.button_pressed(reload):
            response = await make_request()

            e = discord.Embed(title='Awesome Data', description='We can reload this data.')
            e.add_field(name='Random Updating Integer', value=response.get('random_data'))
            await menu.output.edit(embed=e)

        elif menu.button_pressed(close):
            await menu.close()

    page1 = Page(title='Example', description='example')
    page1.on_next(update_data)
    page1.buttons([reload, close])

    quit_page = Page()

    menu = ButtonMenu(ctx).add_pages([page1, quit_page])
    await menu.open()
```

It's a little janky because a menu doesn't expect to only have a single page, so it will require a 'dummy' page (can be empty, as seen above) to pad it. This is something I will change in the next release, though. In addition, I will add the ability for buttons to remain static (ie. prevent them from refreshing if the page did not change, but the embed data did).

**Comment by RaymondLWong** [comment]
Thanks for your help @robertwayne ! I look forward to your next release and will try using your library for my bot.
