### ISSUE TITLE
on_timeout Paginated Menu not working

### ISSUE THREAD

**Issue by filipporomani** [robertwayne/dpymenus#34]
``` py
@bot.command()
async def help(ctx, arg: str =  None):
			
			with open('db/prefixes.json', 'r') as f:
				prefixes=json.load(f)
			pre = prefixes[str(ctx.guild.id)]
			if arg is None:     
				embedVar = Page(title='Help - Page 1', description='')
				embedVar.add_field(
					name=f"**DO NOT DELETE THIS MESSAGE!**",
					value="You have to react with :stop_button: for close the menu! If you delete the message, you will need to wait the next restart to use it again!",
					inline=False)
				embedVar.add_field(
					name=f"{pre}setprefix",
					value="Select your custom prefix! Just type \"/setprefix nd\" where 'nd' is your own custom prefix. If you forgot the prefix simply ping (mention) me. If you need to change the prefix for the 2nd time, use your prefix instead of the first /.",
					inline=False)
				embedVar.add_field(
					name=f"{pre}whitelist",
					value=
					f"Simply whitelist an user from the swear words filter. To use this command type \"{pre}whitelist @user_mention\" where @user_mention is a ping to the user to whitelist.",					
					inline=False)
				embedVar.add_field(
					name=f"{pre}blacklist",
					value=
					f"Simply blacklist an user to the swear words filter. To use this command type \"{pre}blacklist @user_mention\" where @user_mention is a ping to the user to blacklist.",
					inline=False)
				embedVar.add_field(
					name=f"{pre}set-swear",
					value=f"Simply turn ON/OFF the swear word filter, type \"{pre}set-swear on/of\". Use 'off' to disable the filter and 'on' to enable it. ",
					inline=False)
				embedVar.add_field(
					name=f"{pre}ban",
					value=f"Ban a member, use \"{pre}ban @user_mention <optional reason>\".",
					inline=False)
				embedVar.add_field(
					name=f"{pre}kick",
					value=
					f"Kick a member, use \"{pre}kick @user_mention <optional reason>\".",
					inline=False)
				embedVar.add_field(
					name=f"{pre}unban",
					value=f"Unban a member, use \"{pre}unban member_username#XXXX\".",
					inline=False)



				page2 = Page(title='Help - Page 2', description='')
				page2.add_field(
					name=f"{pre}mute",
					value=
					f"Mute an user. To use this command create a \"Muted\" role without the \"Send messages\" permission. Then type \"{pre}mute @user_mention\" where @user_mention is a mention to the user to mute.",
					inline=False)
				page2.add_field(
					name=f"{pre}unmute",
					value=
					f"Unmute an user. To use this command you have to mute the user first and type \"{pre}unmute @user_mention\" where @user_mention is a mention to the user to unmute.",
					inline=False)
				page2.add_field(
					name=f"{pre}new",
					value=
					f"Create a new text channel. Simply use \"{pre}new name of the channel\". ModBot willl automatically convert spaces into \"-\", but you can always add \"-\" beetwen the words.",
					inline=False)
				page2.add_field(
					name=f"{pre}rm",
					value=
					f"Delete a text or a voice channel. You can also use /delete and /remove. For use this command just type \"{pre}rm channel-name\". If the name of the channel as spaces, use \"/rm Channel Name\"."
					.format(ctx.author.mention),
					inline=False)
				page2.add_field(
					name=f"{pre}invite",
					value=
					"Create an instant invite to your server. Note that the generated invite will never expire and it has unlimited uses.",
					inline=False)
				page2.add_field(
					name=f"{pre}ping",
					value="Simply check the bot's ping in milliseconds.",
					inline=False)





				page3 = Page(title='Help - Page 3', description='')
				page3.add_field(
					name=f"{pre}info",
					value=f"Get info of a member, use \"{pre}info @user_mention\".",
					inline=False)
				page3.add_field(
					name=f"{pre}purge",
					value=
					f"Purge as many messages as you want, use \"{pre}purge 1234\" where the 1234 is the number of messages you want to delete.",
					inline=False)
				page3.add_field(
					name=f"{pre}uptime",
					value=
					f"Simply check the bot uptime.",
					inline=False)
				# page3.add_field(
				# 	name=f"{pre}accept",
				# 	value=
				# 	f"Accept the rules at server join (works if server is configured, visit https://modbot.ddns.net/accept to configure). This command is going to be suppressed because of the new Discord update. Use \"{pre}accept.\"",
				# 	inline=False)
				## THE ABOVE COMMAND WAS REMOVED BECAUSE OF THE NEW DISCORD UPDATE ##

				page3.add_field(
					name="More Info",
					value=
					"You can get more info about ModBot on https://modbot.studio. Thanks to ImUsingWinXP#9457 and to Azury#0001 for the help given to build this bot. If you want to DM my creator (filipporomani#0001) just send him a friend request. **ModBot doesn't work in DM.**",
					inline=False)

				menu = PaginatedMenu(ctx)
				menu.persist_on_close()
				menu.show_page_numbers()
				menu.show_skip_buttons()
				menu.show_command_message()
				menu.add_pages([embedVar, page2, page3])
				# async def close():
				# 		await menu.close()
				# embedVar.on_timeout(close)
				# page2.on_timeout(close)
				# page3.on_timeout(close)		
				await menu.open() 

```

Hi, the above is my help's command code. It worked until now; if I use the on_timeout close() function i get this error:

``` 
Ignoring exception in command help:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 249, in help
    await menu.open()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dpymenus/paginated_menu.py", line 171, in open
    await self._handle_transition()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dpymenus/paginated_menu.py", line 309, in _handle_transition
    await transition_map[self.input.name]()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dpymenus/base_menu.py", line 101, in next
    await self._post_next()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dpymenus/base_menu.py", line 204, in _post_next
    await self.send_message(self.page)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dpymenus/paginated_menu.py", line 185, in send_message
    return await self.output.edit(embed=embed)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/message.py", line 1039, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/utils.py", line 316, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Object of type function is not JSON serializable
```

I don't know why, can you please help me @robertwayne ?

**Comment by robertwayne** [comment]
You should be setting the timeout on the menu, not the pages.

`menu.set_timeout(NUMBER_OF_SECONDS)`

This will close the menu already -- so unless you're trying to run some callback in your timeout, which isn't possible without overriding some stuff on the PaginatedMenu base, this should solve your issue.

**Comment by filipporomani** [comment]
Thank you so much for the fast response!
